"use client";

import React from "react";
import { motion } from "framer-motion";
import { FaArrowRight, FaGithub } from "react-icons/fa";

const codeSnippet = `// Generated by Reactify.AI
export function PricingCard({ plan, price }) {
  return (
    <div className="card gradient-border p-8">
      <span className="badge">{plan}</span>
      <h2 className="price">{price}/mo</h2>
      <button className="btn-primary">
        Get started
      </button>
    </div>
  );
}`;

const stats = [
  { value: "10x", label: "Faster development" },
  { value: "500+", label: "Components generated" },
  { value: "99%", label: "Developer satisfaction" },
];

const LandingPage = () => {
  return (
    <section className="relative flex min-h-screen w-full items-center overflow-hidden bg-[#09090B] pt-20">
      {/* Background gradient blobs */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -left-40 h-96 w-96 rounded-full bg-[#00D4FF]/10 blur-3xl" />
        <div className="absolute top-1/3 -right-40 h-96 w-96 rounded-full bg-[#6366F1]/10 blur-3xl" />
        <div className="absolute bottom-0 left-1/2 h-64 w-64 -translate-x-1/2 rounded-full bg-[#00D4FF]/5 blur-3xl" />
      </div>

      {/* Grid pattern */}
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage:
            "linear-gradient(#fff 1px, transparent 1px), linear-gradient(90deg, #fff 1px, transparent 1px)",
          backgroundSize: "60px 60px",
        }}
      />

      <div className="relative mx-auto flex w-full max-w-7xl flex-col items-center gap-16 px-6 py-24 lg:flex-row lg:items-center lg:gap-20">
        {/* Left: Text */}
        <div className="flex flex-col items-start lg:w-1/2">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-1.5 text-sm text-zinc-400"
          >
            <span className="h-2 w-2 rounded-full bg-[#00D4FF] animate-pulse" />
            AI-powered component generation
          </motion.div>

          <motion.h1
            className="mb-6 text-5xl font-black leading-tight tracking-tight text-white sm:text-6xl lg:text-7xl"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            Build React{" "}
            <span className="bg-gradient-to-r from-[#00D4FF] to-[#6366F1] bg-clip-text text-transparent">
              components
            </span>{" "}
            at the speed of thought
          </motion.h1>

          <motion.p
            className="mb-8 max-w-lg text-lg leading-relaxed text-zinc-400"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            Describe what you need in plain English. Reactify.AI generates
            production-ready React components instantly — complete with Tailwind
            styling and clean TypeScript.
          </motion.p>

          <motion.div
            className="flex flex-wrap gap-4"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
          >
            <a
              href="#get-started"
              className="group flex items-center gap-2 rounded-lg bg-white px-6 py-3 text-sm font-semibold text-black transition-all hover:bg-zinc-100 active:scale-95"
            >
              Start building free
              <FaArrowRight className="transition-transform group-hover:translate-x-1" />
            </a>
            <a
              href="https://github.com/Giorgiod91"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-6 py-3 text-sm font-semibold text-white transition-all hover:bg-white/10 active:scale-95"
            >
              <FaGithub />
              View on GitHub
            </a>
          </motion.div>

          <motion.div
            className="mt-12 flex gap-10"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.5 }}
          >
            {stats.map((stat) => (
              <div key={stat.label}>
                <p className="text-2xl font-black text-white">{stat.value}</p>
                <p className="text-sm text-zinc-500">{stat.label}</p>
              </div>
            ))}
          </motion.div>
        </div>

        {/* Right: Code preview */}
        <motion.div
          className="w-full lg:w-1/2"
          initial={{ opacity: 0, x: 40 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          <div className="rounded-2xl border border-white/10 bg-[#111117] shadow-2xl">
            {/* Window chrome */}
            <div className="flex items-center gap-2 border-b border-white/10 px-4 py-3">
              <div className="h-3 w-3 rounded-full bg-[#FF5F57]" />
              <div className="h-3 w-3 rounded-full bg-[#FFBD2E]" />
              <div className="h-3 w-3 rounded-full bg-[#28C840]" />
              <span className="ml-2 text-xs text-zinc-500">
                PricingCard.tsx
              </span>
            </div>
            {/* Code content */}
            <pre className="overflow-x-auto p-6 text-sm leading-relaxed">
              <code>
                {codeSnippet.split("\n").map((line, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: 0.5 + i * 0.05 }}
                    className={
                      line.startsWith("//")
                        ? "text-zinc-600"
                        : line.includes("export") ||
                            line.includes("return") ||
                            line.includes("const")
                          ? "text-[#6366F1]"
                          : line.includes('"')
                            ? "text-[#00D4FF]"
                            : "text-zinc-300"
                    }
                  >
                    {line}
                  </motion.div>
                ))}
              </code>
            </pre>
            {/* Prompt bar */}
            <div className="border-t border-white/10 px-4 py-3">
              <div className="flex items-center gap-3 rounded-lg bg-white/5 px-4 py-2">
                <span className="text-xs text-zinc-500">Prompt</span>
                <motion.span
                  className="text-sm text-zinc-300"
                  animate={{ opacity: [1, 0, 1] }}
                  transition={{ duration: 2, repeat: Infinity, delay: 2 }}
                >
                  A pricing card with gradient border and CTA button
                </motion.span>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default LandingPage;
